### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by AncientGod** [Dekatelon/Weingut#1]
- [ ] Produkte Abschnitt fertigstellen (Ich stelle mir da eine Liste vor etwa in der Form mit unterschiedlichen Feldern die ich dann mit JS befüllen kann: 
![grafik](https://user-images.githubusercontent.com/26146169/27995561-d0bfca72-64d0-11e7-85af-e8d5e3ebe785.png)
Ich bräuchte im Prinzip nur das Skelett, die Daten würde ich dann per DOM einbinden
- [ ] "Unsere Geschichte fertigstellen" (können wir ja ggf. auch entfernen)
- [ ]  "Über Uns" fertigstellen"  (können wir ja ggf. auch entfernen)
- [ ] "Anfahrt" erweitern (optional)
- [ ] Allgemeine Layout Anpassungen
